### ISSUE TITLE
How to preprocess the Data ?

### ISSUE THREAD

**Issue by txAnnie** [shayneobrien/coreference-resolution#4]
How to preprocess the data of OntoNotes Release 5.0 ? I can't open the link you gave in README, the website is gone. So, can you give another link or some other way to show how to preprocess the data ?

**Comment by txAnnie** [comment]
Can you give a sample about the data ?

**Comment by shayneobrien** [comment]
The [link](http://conll.cemantix.org/2012/data.html) to the data and how to process them has been fixed. This page includes a sample of the data. Since OntoNotes files are protected under a license, so I am not able to personally release any of them to others. Best of luck!
